"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var pista_1 = require("./pista");
var administracion_1 = require("./administracion");
var tema1 = new pista_1.Pista(1, "Con una Rubia en el Avion", 3.2, "La Portuaria");
var tema2 = new pista_1.Pista(2, "Playas Oscuras", 2.5, "Los Visitantes");
var tema3 = new pista_1.Pista(3, "Selva", 4, "La Portuaria");
var spotify = new administracion_1.Administrador();
spotify.cargarListaReproduccion([tema1, tema2, tema3]);
spotify.informarDatosLista();
var tema4 = new pista_1.Pista(4, "Mal Bicho", 4.1, "Los Fabulosos Cadillacs");
var tema5 = new pista_1.Pista(5, "19 Dias y 500 Noches", 4.55, "Joaquin Sabina");
spotify.agregarTemaLista(tema4);
spotify.mostrarListaExistente();
spotify.informarDatosLista();
spotify.quitarTemaLista(tema2);
spotify.mostrarListaExistente();
spotify.agregarTemaLista(tema2);
spotify.quitarTemaLista(tema5);
spotify.mostrarListaExistente();
